name: fstore
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.7+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.0+2
  html_unescape: 1.0.1+3
  provider: 3.1.0
  after_layout: 1.0.7+2
  font_awesome_flutter: ^8.5.0
  path: 1.6.4
  vector_math: 2.0.8
  carousel_pro: ^1.0.0
  flutter_widget_from_html_core: ^0.2.3+4
  configurable_expansion_tile: ^1.0.0
  timeago: ^2.0.20
  share: ^0.6.2+3
  validate: ^1.7.0
  country_pickers: ^1.1.0
  shared_preferences: 0.5.3+4
  firebase_messaging: 5.1.6
  firebase_analytics: 5.0.2
  transparent_image: 1.0.0
  pull_to_refresh: ^1.5.7
  localstorage: ^2.0.0
  notification_permissions: ^0.4.3
  flare_splash_screen: 2.1.3
  rate_my_app: ^0.4.0
  flutter_range_slider: ^1.4.0
  page_indicator: ^0.3.0
  extended_image: 0.6.4
  flutter_screenutil: 0.6.0
  fluttertoast: ^3.1.3
  intro_slider: ^2.2.8
  url_launcher: ^5.1.6
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firestore_ui: ^1.7.2
  flutter_webview_plugin: ^0.3.8
  connectivity: ^0.4.4+1
  random_string: ^1.1.0
  google_maps_flutter: 0.5.21+7
  place_picker: 0.9.9
  cached_network_image: ^1.1.1
  image_picker: ^0.6.1+7
  fab_circular_menu: 0.1.1
  uuid: ^2.0.2
  uni_links: ^0.2.0
  flutter_staggered_grid_view: ^0.3.0
  device_apps: ^1.0.8
  auto_size_text: ^2.1.0
  koukicons: ^2.0.1
  lazy_load_scrollview: 1.0.1
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.6
  video_player: ^0.10.2+3
  flutter_spinkit: ^4.0.0
  percent_indicator: ^2.1.1+1
  #youtube_player_flutter: ^5.0.0+1
  animated_text_kit: ^1.3.1
  wave: 0.0.8
  http_auth: ^0.2.5
  international_phone_input: ^1.0.2
  pin_code_fields: ^2.0.2
  cupertino_icons: ^0.1.2
  flutter_facebook_login: ^3.0.0
  webview_flutter: ^0.3.15+1
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^1.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

# Run this script to generate the app icon: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - lib/common/config.json
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
